### ISSUE TITLE
Database Commit Failed! Let's wait a bit!

### ISSUE THREAD

**Issue by ramezeem** [classam/pierc#42]
I run the bot on a centos 7 server with mysql local. only i give after 10 minutes Database Commit Failed! Let's wait a bit! so i must restart the bot and it wil work for 10 min. can i change this? 

thanks

**Comment by cube-drone** [comment]
Yes, make it so that the database commit doesn't fail

**Comment by ramezeem** [comment]
i'm new in this so can you help me with that?

**Comment by cube-drone** [comment]
Nope, you're on your own. :trumpet:
